sudo: false
dist: trusty
language: cpp
services:
- docker
script:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker build -t tylern4/dev-env:python3 rootv6/python3/dev-env/.
- docker build -t tylern4/dev-jupyter:python3 rootv6/python3/dev-jupyter/.
- docker images -a
- docker push tylern4/dev-env:python3
- docker push tylern4/dev-jupyter:python3
